/**
 * RouteEditor.tsx
 * Interactive editor for shuttle route waypoints.
 *
 * Usage:
 *  • Select a route from the sidebar.
 *  • Click the map to add a waypoint.
 *  • Drag any marker to reposition it.
 *  • Type a name in the sidebar to make a waypoint a named stop.
 *  • Use ↑ / ↓ arrows to reorder waypoints.
 *  • Click × to delete a waypoint.
 *  • "Export routes.ts" downloads the complete, corrected shuttleRoutes.ts.
 */

import { useState, useEffect, useRef, useCallback } from 'react';
import maplibregl from 'maplibre-gl';
import { SHUTTLE_ROUTES, TRANSIT_ROW } from '../data/shuttleRoutes';
import { MAP_CONFIG } from '../data/config';

// ─── Types ────────────────────────────────────────────────────────────────────

interface Waypoint {
  id:    string;          // stable React key
  name:  string;          // '' = unnamed path point; non-empty = stop
  coord: [number, number];
}

type RouteWaypoints = Record<string, Waypoint[]>;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function uid(): string {
  return Math.random().toString(36).slice(2, 9);
}

/** Seed waypoints from existing route data (path + stop names merged). */
function seedWaypoints(routeId: string): Waypoint[] {
  const route = SHUTTLE_ROUTES.find(r => r.id === routeId);
  if (!route) return [];

  return route.path.map((coord, i) => {
    const match = route.stops.find(
      s => Math.abs(s.coord[0] - coord[0]) < 0.0002 &&
           Math.abs(s.coord[1] - coord[1]) < 0.0002,
    );
    return { id: `${routeId}-${i}-${uid()}`, name: match?.name ?? '', coord };
  });
}

/** Build the complete shuttleRoutes.ts source from current edit state. */
function generateTs(all: RouteWaypoints): string {
  const header = `/**
 * shuttleRoutes.ts — generated by RouteEditor
 * Generated: ${new Date().toLocaleString()}
 */

export const TRANSIT_ROW: [number, number] = [-84.51451210887464, 39.13430985516541];

export interface ShuttleStop { name: string; coord: [number, number]; }
export interface ShuttleRoute {
  id: string; name: string; color: string;
  isNightride?: boolean;
  stops: ShuttleStop[];
  path:  [number, number][];
}

export const SHUTTLE_ROUTES: ShuttleRoute[] = [`;

  const routes = SHUTTLE_ROUTES.map(route => {
    const wps   = all[route.id] ?? seedWaypoints(route.id);
    const stops = wps
      .filter(w => w.name.trim() !== '')
      .map(w => `      { name: ${JSON.stringify(w.name)}, coord: [${w.coord[0].toFixed(6)}, ${w.coord[1].toFixed(6)}] },`)
      .join('\n');
    const path  = wps
      .map(w => `      [${w.coord[0].toFixed(6)}, ${w.coord[1].toFixed(6)}],`)
      .join('\n');

    return `  {
    id:    ${JSON.stringify(route.id)},
    name:  ${JSON.stringify(route.name)},
    color: ${JSON.stringify(route.color)},${route.isNightride ? '\n    isNightride: true,' : ''}
    stops: [
${stops}
    ],
    path: [
${path}
    ],
  },`;
  }).join('\n\n');

  return `${header}\n${routes}\n];\n`;
}

/** Trigger a file download in the browser. */
function download(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function RouteEditor() {
  const [activeId,   setActiveId]   = useState<string>(SHUTTLE_ROUTES[0].id);
  const [allWps,     setAllWps]     = useState<RouteWaypoints>(() => {
    const init: RouteWaypoints = {};
    SHUTTLE_ROUTES.forEach(r => { init[r.id] = seedWaypoints(r.id); });
    return init;
  });
  const [selected,   setSelected]   = useState<string | null>(null); // highlighted wp id

  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef       = useRef<maplibregl.Map | null>(null);
  const mapLoadedRef = useRef(false);
  const markersRef   = useRef<Map<string, maplibregl.Marker>>(new Map());
  const activeIdRef  = useRef(activeId);
  const allWpsRef    = useRef(allWps);

  useEffect(() => { activeIdRef.current = activeId;  }, [activeId]);
  useEffect(() => { allWpsRef.current   = allWps;    }, [allWps]);

  const activeRoute = SHUTTLE_ROUTES.find(r => r.id === activeId)!;
  const waypoints   = allWps[activeId] ?? [];

  // ── Mutators ───────────────────────────────────────────────────────────────

  const setWaypoints = useCallback((id: string, wps: Waypoint[]) => {
    setAllWps(prev => ({ ...prev, [id]: wps }));
  }, []);

  const addWaypoint = useCallback((coord: [number, number]) => {
    const id  = activeIdRef.current;
    const wps = allWpsRef.current[id] ?? [];
    setAllWps(prev => ({
      ...prev,
      [id]: [...wps, { id: uid(), name: '', coord }],
    }));
  }, []);

  const updateCoord = useCallback((routeId: string, wpId: string, coord: [number, number]) => {
    setAllWps(prev => ({
      ...prev,
      [routeId]: (prev[routeId] ?? []).map(w => w.id === wpId ? { ...w, coord } : w),
    }));
  }, []);

  const updateName = useCallback((wpId: string, name: string) => {
    const id = activeIdRef.current;
    setAllWps(prev => ({
      ...prev,
      [id]: (prev[id] ?? []).map(w => w.id === wpId ? { ...w, name } : w),
    }));
  }, []);

  const deleteWp = useCallback((wpId: string) => {
    const id = activeIdRef.current;
    setAllWps(prev => ({
      ...prev,
      [id]: (prev[id] ?? []).filter(w => w.id !== wpId),
    }));
  }, []);

  const moveWp = useCallback((wpId: string, dir: -1 | 1) => {
    const id  = activeIdRef.current;
    const wps = [...(allWpsRef.current[id] ?? [])];
    const idx = wps.findIndex(w => w.id === wpId);
    if (idx < 0) return;
    const target = idx + dir;
    if (target < 0 || target >= wps.length) return;
    [wps[idx], wps[target]] = [wps[target], wps[idx]];
    setAllWps(prev => ({ ...prev, [id]: wps }));
  }, []);

  const clearRoute = useCallback(() => {
    const id = activeIdRef.current;
    setAllWps(prev => ({ ...prev, [id]: [] }));
  }, []);

  // ── Map init (once) ────────────────────────────────────────────────────────

  useEffect(() => {
    if (!containerRef.current || mapRef.current) return;

    const map = new maplibregl.Map({
      container: containerRef.current,
      style:     MAP_CONFIG.styleUrl,
      center:    TRANSIT_ROW,
      zoom:      14,
    });

    map.addControl(new maplibregl.NavigationControl(), 'top-right');

    map.on('load', () => {
      // Route preview line
      map.addSource('editor-path', {
        type: 'geojson',
        data: { type: 'FeatureCollection', features: [] },
      });
      map.addLayer({
        id: 'editor-path-line',
        type: 'line',
        source: 'editor-path',
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color':     '#E00122',
          'line-width':     2.5,
          'line-opacity':   0.8,
          'line-dasharray': [4, 3],
        },
      });

      // Transit Row marker
      const hubEl = document.createElement('div');
      hubEl.className   = 'sr-hub-marker';
      hubEl.textContent = '★';
      new maplibregl.Marker({ element: hubEl }).setLngLat(TRANSIT_ROW).addTo(map);

      // Click-to-add
      map.on('click', e => {
        // ignore clicks on existing markers
        const hits = map.queryRenderedFeatures(e.point);
        if (hits.length > 0) return;
        addWaypoint([e.lngLat.lng, e.lngLat.lat]);
      });

      mapRef.current    = map;
      mapLoadedRef.current = true;
    });

    return () => {
      markersRef.current.forEach(m => m.remove());
      markersRef.current.clear();
      map.remove();
      mapRef.current       = null;
      mapLoadedRef.current = false;
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ── Sync markers + path line whenever waypoints or active route changes ────

  useEffect(() => {
    const map = mapRef.current;
    if (!map || !mapLoadedRef.current) return;

    const color = activeRoute.color;

    // Remove stale markers
    markersRef.current.forEach((m, id) => {
      if (!waypoints.find(w => w.id === id)) {
        m.remove();
        markersRef.current.delete(id);
      }
    });

    // Add / update markers
    waypoints.forEach((wp, idx) => {
      let marker = markersRef.current.get(wp.id);

      if (!marker) {
        const el = document.createElement('div');
        el.className = 're-marker';
        el.style.setProperty('--route-color', color);

        const label = document.createElement('span');
        label.className = 're-marker__label';
        el.appendChild(label);

        marker = new maplibregl.Marker({ element: el, draggable: true })
          .setLngLat(wp.coord)
          .addTo(map);

        marker.on('dragend', () => {
          const { lng, lat } = marker!.getLngLat();
          updateCoord(activeIdRef.current, wp.id, [lng, lat]);
        });

        markersRef.current.set(wp.id, marker);
      } else {
        marker.setLngLat(wp.coord);
      }

      // Update label
      const el = marker.getElement();
      const label = el.querySelector('.re-marker__label') as HTMLElement | null;
      if (label) {
        label.textContent = wp.name ? wp.name.split(' ').slice(0, 2).join(' ') : String(idx + 1);
      }
      el.classList.toggle('re-marker--stop',    wp.name !== '');
      el.classList.toggle('re-marker--selected', wp.id === selected);
    });

    // Update path line color
    if (map.getLayer('editor-path-line')) {
      map.setPaintProperty('editor-path-line', 'line-color', color);
    }

    // Update path line geometry
    const src = map.getSource('editor-path') as maplibregl.GeoJSONSource | undefined;
    if (src) {
      src.setData({
        type: 'FeatureCollection',
        features: waypoints.length >= 2 ? [{
          type: 'Feature',
          geometry: { type: 'LineString', coordinates: waypoints.map(w => w.coord) },
          properties: {},
        }] : [],
      });
    }
  }, [waypoints, activeRoute, selected, updateCoord]);

  // ── Scroll sidebar row into view when selected ─────────────────────────────

  const sidebarRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!selected || !sidebarRef.current) return;
    const el = sidebarRef.current.querySelector(`[data-wpid="${selected}"]`) as HTMLElement | null;
    el?.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
  }, [selected]);

  // ── Fly to marker when selected in sidebar ─────────────────────────────────

  const flyToWp = useCallback((wp: Waypoint) => {
    setSelected(wp.id);
    mapRef.current?.flyTo({ center: wp.coord, zoom: 16, duration: 600 });
  }, []);

  // ─── Render ───────────────────────────────────────────────────────────────

  const stopCount = waypoints.filter(w => w.name).length;

  return (
    <div className="re-page">

      {/* ── Sidebar ─────────────────────────────────────────────── */}
      <aside className="re-sidebar">
        <div className="re-sidebar__inner">

          {/* Route selector */}
          <div className="section-label">Edit Routes</div>
          <div className="re-field">
            <label className="fp-field__label" htmlFor="re-route-select">Route</label>
            <select
              id="re-route-select"
              value={activeId}
              onChange={e => { setActiveId(e.target.value); setSelected(null); }}
            >
              {SHUTTLE_ROUTES.map(r => (
                <option key={r.id} value={r.id}>{r.name}</option>
              ))}
            </select>
          </div>

          {/* Instructions */}
          <div className="re-instructions">
            <span className="re-instructions__icon">👆</span>
            Click map to add a waypoint.<br />
            Drag markers to reposition.<br />
            Name a waypoint to make it a stop.
          </div>

          {/* Stats */}
          <div className="re-stats">
            <span>{waypoints.length} waypoints</span>
            <span className="re-stats__sep">·</span>
            <span>{stopCount} named stops</span>
          </div>

          {/* Waypoint list */}
          <div className="re-wp-list" ref={sidebarRef}>
            {waypoints.length === 0 && (
              <div className="re-empty">No waypoints yet.<br />Click the map to start.</div>
            )}
            {waypoints.map((wp, idx) => (
              <div
                key={wp.id}
                data-wpid={wp.id}
                className={`re-wp-item${wp.id === selected ? ' re-wp-item--selected' : ''}`}
                onClick={() => flyToWp(wp)}
              >
                <span
                  className="re-wp-num"
                  style={{ background: activeRoute.color }}
                >
                  {idx + 1}
                </span>
                <input
                  className="re-wp-name"
                  placeholder="Stop name (optional)"
                  value={wp.name}
                  onClick={e => e.stopPropagation()}
                  onChange={e => updateName(wp.id, e.target.value)}
                />
                <span className="re-wp-coords">
                  {wp.coord[1].toFixed(5)}, {wp.coord[0].toFixed(5)}
                </span>
                <div className="re-wp-actions">
                  <button
                    className="re-wp-btn"
                    title="Move up"
                    disabled={idx === 0}
                    onClick={e => { e.stopPropagation(); moveWp(wp.id, -1); }}
                  >↑</button>
                  <button
                    className="re-wp-btn"
                    title="Move down"
                    disabled={idx === waypoints.length - 1}
                    onClick={e => { e.stopPropagation(); moveWp(wp.id, 1); }}
                  >↓</button>
                  <button
                    className="re-wp-btn re-wp-btn--delete"
                    title="Delete waypoint"
                    onClick={e => { e.stopPropagation(); deleteWp(wp.id); if (selected === wp.id) setSelected(null); }}
                  >×</button>
                </div>
              </div>
            ))}
          </div>

          {/* Actions */}
          <div className="re-actions">
            <button
              className="re-action-btn re-action-btn--danger"
              onClick={clearRoute}
              disabled={waypoints.length === 0}
            >
              Clear route
            </button>
            <button
              className="re-action-btn re-action-btn--primary"
              onClick={() => download('shuttleRoutes.ts', generateTs(allWps))}
            >
              Export routes.ts ↓
            </button>
          </div>

        </div>
      </aside>

      {/* ── Map ─────────────────────────────────────────────────── */}
      <main className="re-map-wrap" role="main" aria-label="Route editor map">
        <div ref={containerRef} style={{ width: '100%', height: '100%' }} />
        <div className="re-map-hint">
          Editing: <strong>{activeRoute.name}</strong>
          <span
            className="re-map-hint__swatch"
            style={{ background: activeRoute.color }}
          />
        </div>
      </main>

    </div>
  );
}
