name: Deploy Website

on:
  push:
    branches:
      - update_deploy_actions
      - main
  pull_request:
    branches:
      - update_deploy_actions
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    name: setup  
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

    #   - name: Setup Node.js
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: 22
    #       cache: npm
    
    #   - name: Clean npm
    #     run: |
    #         rm -rf node_modules package-lock.json

      - name: Install npm
        run: npm install

    #   - name: Package Install
    #     run: npm ci

      - name: Build
        run: npm run build

      # Deploy to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=ucnavvy

    #   - name: Upload Artifacts
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: build-artifacts
    #       path: 'dist/**'